import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { formatDate, taskStatusLabel } from "@/lib/format";
import { trpc } from "@/lib/trpc";
import { CheckCircle2, ListChecks } from "lucide-react";
import { useState } from "react";
import { useLocation } from "wouter";

const statuses = ["all", "todo", "in_progress", "review", "completed"] as const;
export default function MyTasks() { const [, setLocation] = useLocation(); const [filter, setFilter] = useState<(typeof statuses)[number]>("all"); const { data, isLoading } = trpc.collaboration.dashboard.summary.useQuery(); const tasks = (data?.myTasks ?? []).filter((task) => filter === "all" || task.status === filter);
  return <div className="space-y-7"><div><p className="text-sm font-semibold text-[#2457d6]">MY TASKS</p><h1 className="mt-1 font-display text-3xl font-extrabold tracking-tight">Your focused work.</h1><p className="mt-2 text-slate-500">All work assigned to you, organized by status.</p></div><div className="flex flex-wrap gap-2">{statuses.map((status) => <Button key={status} variant={filter === status ? "default" : "outline"} onClick={() => setFilter(status)} className={filter === status ? "rounded-xl bg-[#2457d6]" : "rounded-xl bg-white capitalize"}>{status === "all" ? "All tasks" : taskStatusLabel(status)}</Button>)}</div><div className="overflow-hidden rounded-2xl border border-slate-200/80 bg-white shadow-sm"><div className="grid grid-cols-[minmax(180px,1.8fr)_minmax(130px,1fr)_110px_115px] gap-4 border-b border-slate-100 px-5 py-3 text-xs font-bold uppercase tracking-wider text-slate-400"><span>Task</span><span className="hidden sm:block">Project</span><span>Status</span><span>Due</span></div>{isLoading ? <p className="p-8 text-sm text-slate-500">Loading your tasks…</p> : tasks.length ? tasks.map((task) => <button key={task.id} onClick={() => setLocation(`/projects/${task.projectId}?task=${task.id}`)} className="grid w-full grid-cols-[minmax(180px,1.8fr)_minmax(130px,1fr)_110px_115px] gap-4 border-b border-slate-100 px-5 py-4 text-left transition hover:bg-slate-50"><div className="min-w-0"><p className="truncate text-sm font-semibold">{task.title}</p><p className="mt-1 truncate text-xs text-slate-500 sm:hidden">{task.projectName}</p></div><p className="hidden truncate text-sm text-slate-500 sm:block">{task.projectName}</p><Badge className="h-fit w-fit rounded-md border-0 bg-blue-50 px-2 py-1 text-[10px] text-blue-700">{taskStatusLabel(task.status)}</Badge><span className="text-sm text-slate-500">{formatDate(task.dueDate)}</span></button>) : <div className="flex flex-col items-center p-12 text-center"><div className="grid h-12 w-12 place-items-center rounded-xl bg-slate-100 text-slate-500"><ListChecks className="h-6 w-6" /></div><p className="mt-4 font-semibold">No tasks assigned</p><p className="mt-1 text-sm text-slate-500">You’re all clear for this status.</p><CheckCircle2 className="mt-4 h-5 w-5 text-emerald-500" /></div>}</div></div>; }
