import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { formatDate, initials } from "@/lib/format";
import { trpc } from "@/lib/trpc";
import { Camera, ShieldCheck } from "lucide-react";
import { useEffect, useState } from "react";
import { toast } from "sonner";
export default function Profile() { const { data, isLoading } = trpc.collaboration.users.profile.useQuery(); const utils = trpc.useUtils(); const [name, setName] = useState(""); const [avatar, setAvatar] = useState(""); useEffect(() => { if (data) { setName(data.name || ""); setAvatar((data as { avatar?: string | null }).avatar || ""); } }, [data]); const update = trpc.collaboration.users.updateProfile.useMutation({ onSuccess: () => { toast.success("Changes saved"); void utils.collaboration.users.profile.invalidate(); }, onError: (error) => toast.error(error.message) }); if (isLoading) return <p className="text-sm text-slate-500">Loading profile…</p>; return <div className="mx-auto max-w-3xl space-y-7"><div><p className="text-sm font-semibold text-[#2457d6]">PROFILE</p><h1 className="mt-1 font-display text-3xl font-extrabold tracking-tight">Personal details.</h1><p className="mt-2 text-slate-500">Manage the details your teammates see in project workspaces.</p></div><div className="rounded-2xl border border-slate-200/80 bg-white p-6 shadow-sm"><div className="flex flex-col gap-6 sm:flex-row sm:items-center"><Avatar className="h-20 w-20"><AvatarImage src={avatar || undefined} /><AvatarFallback className="bg-blue-100 text-lg font-bold text-[#2457d6]">{initials(name)}</AvatarFallback></Avatar><div><p className="font-display text-xl font-bold">{data?.name || "Team member"}</p><p className="mt-1 text-sm text-slate-500">{data?.email || "Authenticated account"}</p><p className="mt-2 flex items-center gap-1 text-xs font-semibold text-emerald-600"><ShieldCheck className="h-3.5 w-3.5" />Secure authenticated account</p></div></div><div className="mt-8 grid gap-5 border-t border-slate-100 pt-6"><div className="grid gap-2"><Label htmlFor="profile-name">Full name</Label><Input id="profile-name" value={name} onChange={(event) => setName(event.target.value)} className="max-w-lg rounded-xl" /></div><div className="grid gap-2"><Label htmlFor="avatar-url">Profile image URL</Label><div className="flex max-w-lg gap-2"><Input id="avatar-url" value={avatar} onChange={(event) => setAvatar(event.target.value)} placeholder="https://…" className="rounded-xl" /><Camera className="mt-2.5 h-4 w-4 text-slate-400" /></div></div><div className="grid gap-2"><Label>Account information</Label><p className="text-sm text-slate-500">Role: <span className="font-medium capitalize text-slate-700">{data?.role || "user"}</span> · Joined {formatDate(data?.createdAt)}</p></div><div><Button onClick={() => update.mutate({ name, avatar: avatar || null })} disabled={update.isPending} className="rounded-xl bg-[#2457d6]">{update.isPending ? "Saving…" : "Save profile"}</Button></div></div></div></div>; }
