import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { formatDate } from "@/lib/format";
import { trpc } from "@/lib/trpc";
import { CalendarDays, Edit3, FolderKanban, Plus, Search, Trash2, Users } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import { useLocation } from "wouter";

type ProjectDraft = { name: string; description: string; startDate: string; dueDate: string };
const emptyDraft: ProjectDraft = { name: "", description: "", startDate: "", dueDate: "" };

function toDate(value: string) { return value ? new Date(`${value}T00:00:00`) : null; }
function inputDate(value?: Date | string | null) { return value ? new Date(value).toISOString().slice(0, 10) : ""; }

export default function Projects() {
  const [, setLocation] = useLocation();
  const utils = trpc.useUtils();
  const [search, setSearch] = useState("");
  const [open, setOpen] = useState(false);
  const [editing, setEditing] = useState<{ id: number; draft: ProjectDraft } | null>(null);
  const [draft, setDraft] = useState<ProjectDraft>(emptyDraft);
  const query = trpc.collaboration.projects.list.useQuery(search.trim() ? { search: search.trim() } : undefined);
  const create = trpc.collaboration.projects.create.useMutation({ onSuccess: ({ id }) => { toast.success("Project created successfully"); void utils.collaboration.projects.list.invalidate(); setOpen(false); setDraft(emptyDraft); setLocation(`/projects/${id}`); }, onError: (error) => toast.error(error.message) });
  const update = trpc.collaboration.projects.update.useMutation({ onSuccess: () => { toast.success("Changes saved"); void utils.collaboration.projects.list.invalidate(); setEditing(null); }, onError: (error) => toast.error(error.message) });
  const remove = trpc.collaboration.projects.remove.useMutation({ onSuccess: () => { toast.success("Project deleted"); void utils.collaboration.projects.list.invalidate(); }, onError: (error) => toast.error(error.message) });
  const submit = () => {
    if (!draft.name.trim()) return toast.error("Project name is required.");
    const input = { name: draft.name.trim(), description: draft.description.trim() || undefined, startDate: toDate(draft.startDate), dueDate: toDate(draft.dueDate) };
    if (editing) update.mutate({ id: editing.id, ...input }); else create.mutate(input);
  };
  const projects = query.data ?? [];
  return <div className="space-y-7"><section className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-semibold text-[#2457d6]">PROJECTS</p><h1 className="mt-1 font-display text-3xl font-extrabold tracking-tight">Plan work with clarity.</h1><p className="mt-2 text-slate-500">Create shared spaces for focused delivery and team momentum.</p></div><Button onClick={() => { setDraft(emptyDraft); setOpen(true); }} className="h-11 rounded-xl bg-[#2457d6] px-5"><Plus className="mr-2 h-4 w-4" />Create project</Button></section>
    <div className="relative max-w-md"><Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" /><Input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search projects…" className="h-11 rounded-xl border-slate-200 bg-white pl-9 shadow-sm" /></div>
    {query.isLoading ? <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{Array.from({ length: 6 }).map((_, index) => <div key={index} className="h-64 animate-pulse rounded-2xl bg-slate-200/70" />)}</div> : projects.length ? <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{projects.map((project) => <article key={project.id} className="group flex min-h-64 flex-col rounded-2xl border border-slate-200/90 bg-white p-6 shadow-sm transition duration-200 hover:-translate-y-0.5 hover:shadow-lg hover:shadow-slate-200/60"><div className="flex items-start justify-between gap-3"><button onClick={() => setLocation(`/projects/${project.id}`)} className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-blue-50 font-display font-extrabold text-[#2457d6]">{project.name.slice(0, 2).toUpperCase()}</button><div className="flex gap-1"><button onClick={() => { setDraft({ name: project.name, description: project.description || "", startDate: inputDate(project.startDate), dueDate: inputDate(project.dueDate) }); setEditing({ id: project.id, draft }); }} className="rounded-lg p-2 text-slate-400 opacity-100 hover:bg-slate-100 hover:text-slate-700 sm:opacity-0 sm:group-hover:opacity-100" aria-label="Edit project"><Edit3 className="h-4 w-4" /></button>{project.role === "owner" && <button onClick={() => { if (confirm(`Delete ${project.name}? This cannot be undone.`)) remove.mutate({ id: project.id }); }} className="rounded-lg p-2 text-slate-400 opacity-100 hover:bg-rose-50 hover:text-rose-600 sm:opacity-0 sm:group-hover:opacity-100" aria-label="Delete project"><Trash2 className="h-4 w-4" /></button>}</div></div><button onClick={() => setLocation(`/projects/${project.id}`)} className="mt-5 text-left"><div className="flex items-center gap-2"><h2 className="truncate font-display text-lg font-bold">{project.name}</h2><Badge variant="secondary" className="rounded-md bg-slate-100 text-[10px] capitalize text-slate-600">{project.role}</Badge></div><p className="mt-2 line-clamp-2 min-h-10 text-sm leading-5 text-slate-500">{project.description || "No description added yet."}</p></button><div className="mt-auto pt-6"><div className="mb-2 flex items-center justify-between text-xs"><span className="font-semibold text-slate-500">Progress</span><span className="font-bold text-slate-700">{project.progress}%</span></div><div className="h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-[#2457d6]" style={{ width: `${project.progress}%` }} /></div><div className="mt-5 flex items-center justify-between text-xs text-slate-500"><span className="flex items-center gap-1"><Users className="h-3.5 w-3.5" />{project.total} tasks</span><span className="flex items-center gap-1"><CalendarDays className="h-3.5 w-3.5" />{formatDate(project.dueDate)}</span></div></div></article>)}</div> : <EmptyProjects onCreate={() => { setDraft(emptyDraft); setOpen(true); }} />}
    <ProjectDialog open={open || Boolean(editing)} onOpenChange={(value) => { if (!value) { setOpen(false); setEditing(null); } }} title={editing ? "Edit project" : "Create a new project"} description={editing ? "Keep project details accurate for your team." : "Set the project context, then invite your team from its workspace."} draft={draft} setDraft={setDraft} onSubmit={submit} submitting={create.isPending || update.isPending} submitLabel={editing ? "Save changes" : "Create project"} />
  </div>;
}

export function ProjectDialog({ open, onOpenChange, title, description, draft, setDraft, onSubmit, submitting, submitLabel }: { open: boolean; onOpenChange: (value: boolean) => void; title: string; description: string; draft: ProjectDraft; setDraft: (draft: ProjectDraft) => void; onSubmit: () => void; submitting: boolean; submitLabel: string }) {
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-w-xl rounded-2xl"><DialogHeader><DialogTitle className="font-display text-xl">{title}</DialogTitle><DialogDescription>{description}</DialogDescription></DialogHeader><div className="grid gap-5 py-3"><div className="grid gap-2"><Label htmlFor="project-name">Project name</Label><Input id="project-name" value={draft.name} onChange={(event) => setDraft({ ...draft, name: event.target.value })} placeholder="e.g. Website launch" className="rounded-xl" autoFocus /></div><div className="grid gap-2"><Label htmlFor="project-description">Description</Label><Textarea id="project-description" value={draft.description} onChange={(event) => setDraft({ ...draft, description: event.target.value })} placeholder="What will the team deliver?" className="min-h-28 rounded-xl" /></div><div className="grid gap-4 sm:grid-cols-2"><div className="grid gap-2"><Label htmlFor="start-date">Start date</Label><Input id="start-date" type="date" value={draft.startDate} onChange={(event) => setDraft({ ...draft, startDate: event.target.value })} className="rounded-xl" /></div><div className="grid gap-2"><Label htmlFor="due-date">Due date</Label><Input id="due-date" type="date" value={draft.dueDate} onChange={(event) => setDraft({ ...draft, dueDate: event.target.value })} className="rounded-xl" /></div></div></div><div className="flex justify-end gap-3"><Button variant="outline" onClick={() => onOpenChange(false)} className="rounded-xl">Cancel</Button><Button disabled={submitting} onClick={onSubmit} className="rounded-xl bg-[#2457d6]">{submitting ? "Saving…" : submitLabel}</Button></div></DialogContent></Dialog>;
}

function EmptyProjects({ onCreate }: { onCreate: () => void }) { return <div className="flex min-h-80 flex-col items-center justify-center rounded-2xl border border-dashed border-slate-300 bg-white p-8 text-center"><div className="grid h-14 w-14 place-items-center rounded-2xl bg-blue-50 text-[#2457d6]"><FolderKanban className="h-7 w-7" /></div><h2 className="mt-5 font-display text-xl font-bold">No projects yet</h2><p className="mt-2 max-w-sm text-sm text-slate-500">Create your first project to organize tasks, share context, and collaborate with your team.</p><Button onClick={onCreate} className="mt-6 rounded-xl bg-[#2457d6]"><Plus className="mr-2 h-4 w-4" />Create project</Button></div>; }
